import type { GetStaticProps } from 'next';
import Head from 'next/head';
import About from '../components/About';
import ContactMe from '../components/ContactMe';
import Experience from '../components/Experience';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Projects from '../components/Projects';
import Skills from '../components/Skills';
import { ArrowUpCircleIcon } from '@heroicons/react/24/solid';
import Link from 'next/link';
import {
	Experience as TExperience,
	PageInfo,
	Skill,
	Project,
	Social,
} from '../typings';
import fetchPageInfo from '../utils/fetchPageInfo';
import fetchSkills from '../utils/fetchSkills';
import fetchSocials from '../utils/fetchSocials';
import fetchProjects from '../utils/fetchProject';
import fetchExperience from '../utils/fetchExperience';

type Props = {
	pageInfo: PageInfo;
	experiences: TExperience[];
	skills: Skill[];
	socials: Social[];
	projects: Project[];
};

const Home = ({ pageInfo, projects, skills, socials, experiences }: Props) => {
	return (
		<div className='bg-[rgb(36,36,36)] text-white h-screen z-0 overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-thumb-[#F7AB0A] scrollbar-track-gray-400/20'>
			<Head>
				<title>Olaoluwa Vincent</title>
				<meta
					name='description'
					content='Generated by Olaoluwa Vincent'
				/>
			</Head>
			<Header socials={socials} />
			{/* Sections */}
			<section className='space-y-5'>
				<section id='hero' className=''>
					<Hero pageInfo={pageInfo} />
				</section>
				<section id='about' className=''>
					<About pageInfo={pageInfo} />
				</section>
				<section id='experience' className=''>
					<Experience experiences={experiences} />
				</section>
				<section id='skills' className=''>
					<Skills skills={skills} />
				</section>
				<section id='projects' className=''>
					<Projects projects={projects} />
				</section>
				<section id='contact' className='pb-10'>
					<ContactMe pageInfo={pageInfo} />
				</section>
			</section>
			{/* <Link href={'#hero'} className=''>
				<footer className='sticky bottom-10 md:bottom-5 left-2 w-full cursor-pointer z-50'>
					<ArrowUpCircleIcon className='w-10 h-10 hover:fill-slate-500' />
				</footer>
			</Link> */}
		</div>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
	const pageInfo = await fetchPageInfo();
	const skills = await fetchSkills();
	const socials = await fetchSocials();
	const projects = await fetchProjects();
	const experiences = await fetchExperience();

	return {
		props: {
			pageInfo,
			skills,
			socials,
			projects,
			experiences,
		},
		// Next.js will revalidate the pages after the stipulated
		// amount of time specified in Seconds
		revalidate: 10,
	};
};
