import type { GetStaticProps } from 'next';
import Head from 'next/head';
import About from '../components/About';
import ContactMe from '../components/ContactMe';
import Experience from '../components/Experience';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Projects from '../components/Projects';
import Skills from '../components/Skills';
import { ArrowUpCircleIcon } from '@heroicons/react/24/solid';
import Link from 'next/link';
import {
	Experience as TExperience,
	PageInfo,
	Skill,
	Project,
	Social,
} from '../typings';
// import { fetchProjects } from '../utils/fetchProject';
// import { fetchPageInfo } from '../utils/fetchPageInfo';
// import { fetchSkills } from '../utils/fetchSkills';
// import { fetchSocials } from '../utils/fetchSocials';
// import { fetchExperiences } from '../utils/fecthExperience';
import getPageInfo from './api/getPageInfo';
import getSkills from './api/getSkills';
import getSocials from './api/getSocials';
import getProjects from './api/getProjects';
import getExperience from './api/getExperiences';

type Props = {
	pageInfo: PageInfo;
	experiences: TExperience[];
	skills: Skill[];
	socials: Social[];
	projects: Project[];
};

const Home = ({ pageInfo, projects, skills, socials, experiences }: Props) => {
	console.log(socials);
	return (
		<div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory z-0 overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-thumb-[#F7AB0A] scrollbar-track-gray-400/20'>
			<Head>
				<title>Olaoluwa Vincent</title>
				<meta
					name='description'
					content='Generated by Olaoluwa Vincent'
				/>
			</Head>
			<Header socials={socials} />
			<section id='hero' className='snap-start'>
				<Hero pageInfo={pageInfo} />
			</section>
			<section id='about' className='snap-center'>
				<About pageInfo={pageInfo} />
			</section>
			<section id='experience' className='snap-center'>
				<Experience experiences={experiences} />
			</section>
			<section id='skills' className='snap-start'>
				<Skills skills={skills} />
			</section>
			<section id='projects' className='snap-start'>
				<Projects projects={projects} />
			</section>
			<section id='contact' className='snap-start'>
				<ContactMe pageInfo={pageInfo} />
			</section>

			<Link href={'#hero'} className=''>
				<footer className='sticky bottom-5 right-0 w-full cursor-pointer'>
					<ArrowUpCircleIcon className='w-10 h-10 hover:fill-slate-500' />
				</footer>
			</Link>
		</div>
	);
};

export default Home;

export const getStaticProps = async () => {
	const pageInfo = await getPageInfo;
	const skills = await getSkills;
	const socials = await getSocials;
	const projects = await getProjects;
	const experiences = await getExperience;

	return {
		props: {
			pageInfo,
			skills,
			socials,
			projects,
			experiences,
		},
		// Next.js will revalidate the pages after the stipulated
		// amount of time specified in Seconds
		revalidate: 60,
	};
};
